#!/usr/bin/env bash


i=1
# list-based for loop
for fruit in apple pear banana kiwi; do
	echo "yummy fruit $i: $fruit"
	((i+=1))
done

# range-based for loop (brace expansion)
for i in {1..5}; do 
	echo "$i"
done 